In [1]:
# Import dependencies
import pandas as pd
import numpy as np

In [2]:
file_path = "./Resources/energy_data.csv"
energy_df = pd.read_csv(file_path)
energy_df.head()

,State,Year,Production.Coal,Consumption.Commercial.Coal,Consumption.Commercial.Distillate Fuel Oil,Consumption.Commercial.Geothermal,Consumption.Commercial.Hydropower,Consumption.Commercial.Kerosene,Consumption.Commercial.Petroleum,Consumption.Commercial.Natural Gas,...,Price.Industrial.Coal,Price.Industrial.Distillate Fuel Oil,Price.Industrial.Kerosene,Price.Industrial.Petroleum,Price.Industrial.Natural Gas,Price.Industrial.Other Petroleum Products,Price.Transportation.Coal,Price.Transportation.Distillate Fuel Oil,Price.Transportation.Petroleum,Price.Transportation.Natural Gas
0,Alaska,1960,11263,496,1562,0,0,0,5230,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Alaska,1961,11497,496,1646,0,0,0,5304,122,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Alaska,1962,13588,593,1732,0,0,0,5251,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Alaska,1963,13307,393,1868,0,0,0,5475,1632,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Alaska,1964,11622,306,2020,0,0,0,7242,1944,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
energy09_19_df = energy_df.loc[energy_df["Year"] >= 2009]
energy09_19_df.head()

,State,Year,Production.Coal,Consumption.Commercial.Coal,Consumption.Commercial.Distillate Fuel Oil,Consumption.Commercial.Geothermal,Consumption.Commercial.Hydropower,Consumption.Commercial.Kerosene,Consumption.Commercial.Petroleum,Consumption.Commercial.Natural Gas,...,Price.Industrial.Coal,Price.Industrial.Distillate Fuel Oil,Price.Industrial.Kerosene,Price.Industrial.Petroleum,Price.Industrial.Natural Gas,Price.Industrial.Other Petroleum Products,Price.Transportation.Coal,Price.Transportation.Distillate Fuel Oil,Price.Transportation.Petroleum,Price.Transportation.Natural Gas
49,Alaska,2009,29016,8098,6315,74,0,67,7412,16701,...,2.72,17.48,16.37,16.28,0.00,0.0,0.0,24.24,17.88,11.92
50,Alaska,2010,33556,8533,11111,74,0,92,12575,15998,...,2.87,21.37,20.42,20.75,0.00,0.0,0.0,25.53,20.86,12.83
51,Alaska,2011,33524,9432,10060,88,0,104,11438,19647,...,3.65,29.58,27.22,26.09,0.00,0.0,0.0,30.94,27.20,9.76
52,Alaska,2012,31332,9201,8541,85,0,79,9806,20135,...,3.95,27.41,28.09,26.23,0.00,0.0,0.0,31.99,27.97,10.93
53,Alaska,2013,24917,8939,6743,85,0,27,7965,18711,...,4.72,27.40,27.39,26.00,8.15,0.0,0.0,31.64,27.06,8.33

In [5]:
energy09_19_df.isnull().any()

State                                         False
Year                                          False
Production.Coal                               False
Consumption.Commercial.Coal                   False
Consumption.Commercial.Distillate Fuel Oil    False
                                              ...
Price.Industrial.Other Petroleum Products     False
Price.Transportation.Coal                     False
Price.Transportation.Distillate Fuel Oil      False
Price.Transportation.Petroleum                False
Price.Transportation.Natural Gas              False
Length: 84, dtype: bool